package dev.redstoneengineering.blockentity;
import dev.redstoneengineering.RedstoneEngineering;import net.minecraft.core.*;import net.minecraft.core.HolderLookup;import net.minecraft.nbt.CompoundTag;import net.minecraft.world.level.block.entity.BlockEntity;import net.minecraft.world.level.block.state.BlockState;
/** Four-channel logic analyzer with edge trigger and cursor timing. */
public class LogicAnalyzerBlockEntity extends BlockEntity{
 private static final int CAP=32;private final int[]m=new int[CAP],v=new int[CAP],rise=new int[4],fall=new int[4];private int index=0,count=0,lastMask=0,lastValid=0,triggerChannel=0,triggerEdge=1,cursorA=0,cursorB=8;private boolean armed=true,triggered=false;private int post=0;
 public LogicAnalyzerBlockEntity(BlockPos p,BlockState s){super(RedstoneEngineering.LOGIC_ANALYZER_BLOCK_ENTITY.get(),p,s);}
 public void addSample(int mask,int valid){int common=valid&lastValid;boolean fire=false;for(int c=0;c<4;c++){int bit=1<<c;if((common&bit)==0)continue;boolean before=(lastMask&bit)!=0,now=(mask&bit)!=0;if(!before&&now)rise[c]++;if(before&&!now)fall[c]++;if(armed&&c==triggerChannel&&((triggerEdge==1&&!before&&now)||(triggerEdge==2&&before&&!now)))fire=true;}if(armed||triggered){m[index]=mask;v[index]=valid;if(armed&&fire){armed=false;triggered=true;post=0;}if(triggered)post++;index=(index+1)%CAP;count=Math.min(CAP,count+1);if(triggered&&post>=CAP/2)triggered=false;}lastMask=mask;lastValid=valid;setChanged();}
 public void clear(){for(int i=0;i<CAP;i++){m[i]=0;v[i]=0;}for(int i=0;i<4;i++){rise[i]=0;fall[i]=0;}index=count=lastMask=lastValid=0;armed=true;triggered=false;post=0;setChanged();}
 public void arm(){armed=true;triggered=false;post=0;setChanged();} public void cycleTriggerChannel(){triggerChannel=(triggerChannel+1)%4;arm();} public void cycleTriggerEdge(){triggerEdge=triggerEdge==1?2:1;arm();}
 public void moveCursorA(){cursorA=(cursorA+1)%16;setChanged();}public void moveCursorB(){cursorB=(cursorB+1)%16;setChanged();}public int cursorDeltaSamples(){return Math.abs(cursorB-cursorA);}public String triggerStatus(){return "CH"+(triggerChannel+1)+" "+(triggerEdge==1?"RISING":"FALLING")+" "+(armed?"ARMED":triggered?"TRIGGERED":"HOLD");}
 public int rising(int c){return rise[c];}public int falling(int c){return fall[c];}
 public int highSamples(int c){int bit=1<<c,n=0;for(int i=0;i<count;i++){int src=(index-count+i+CAP)%CAP;if((v[src]&bit)!=0&&(m[src]&bit)!=0)n++;}return n;}public int validSamples(int c){int bit=1<<c,n=0;for(int i=0;i<count;i++)if((v[(index-count+i+CAP)%CAP]&bit)!=0)n++;return n;}public int dutyPercent(int c){int n=validSamples(c);return n==0?0:(highSamples(c)*100)/n;}
 public String waveform(int c){if(count==0)return"∅";StringBuilder b=new StringBuilder();int s=Math.max(0,count-16),bit=1<<c;for(int i=s;i<count;i++){int src=(index-count+i+CAP)%CAP;b.append((v[src]&bit)==0?'·':(m[src]&bit)!=0?'█':'_');}return b.toString();}
 @Override protected void loadAdditional(CompoundTag t,HolderLookup.Provider r){super.loadAdditional(t,r);copy(t.getIntArray("masks"),m);copy(t.getIntArray("validMasks"),v);copy(t.getIntArray("rising"),rise);copy(t.getIntArray("falling"),fall);index=Math.max(0,Math.min(CAP-1,t.getInt("index")));count=Math.max(0,Math.min(CAP,t.getInt("count")));lastMask=t.getInt("lastMask");lastValid=t.getInt("lastValidMask");triggerChannel=Math.max(0,Math.min(3,t.getInt("triggerChannel")));triggerEdge=Math.max(1,Math.min(2,t.getInt("triggerEdge")));cursorA=Math.max(0,Math.min(15,t.getInt("cursorA")));cursorB=Math.max(0,Math.min(15,t.getInt("cursorB")));armed=t.getBoolean("armed");triggered=t.getBoolean("triggered");}
 private static void copy(int[]s,int[]d){for(int i=0;i<Math.min(s.length,d.length);i++)d[i]=s[i];}
 @Override protected void saveAdditional(CompoundTag t,HolderLookup.Provider r){super.saveAdditional(t,r);t.putIntArray("masks",m);t.putIntArray("validMasks",v);t.putIntArray("rising",rise);t.putIntArray("falling",fall);t.putInt("index",index);t.putInt("count",count);t.putInt("lastMask",lastMask);t.putInt("lastValidMask",lastValid);t.putInt("triggerChannel",triggerChannel);t.putInt("triggerEdge",triggerEdge);t.putInt("cursorA",cursorA);t.putInt("cursorB",cursorB);t.putBoolean("armed",armed);t.putBoolean("triggered",triggered);}
}
