package dev.redstoneengineering.block;
import com.mojang.serialization.MapCodec;import dev.redstoneengineering.*;import dev.redstoneengineering.physics.RuntimeIntStore;import net.minecraft.core.*;import net.minecraft.network.chat.Component;import net.minecraft.server.level.ServerLevel;import net.minecraft.util.RandomSource;import net.minecraft.world.*;import net.minecraft.world.entity.player.Player;import net.minecraft.world.item.context.BlockPlaceContext;import net.minecraft.world.level.*;import net.minecraft.world.level.block.Block;import net.minecraft.world.level.block.state.*;import net.minecraft.world.level.block.state.properties.*;import net.minecraft.world.phys.BlockHitResult;import javax.annotation.Nullable;
/** Mechatronic servo primitive. BACK=position command, RIGHT=inhibit; finite slew plus trajectory diagnostics. */
public class ServoActuatorBlock extends Block{
 public static final DirectionProperty FACING=BlockStateProperties.HORIZONTAL_FACING;public static final IntegerProperty SLEW=IntegerProperty.create("slew",0,2);private static final int[]STEP={1,2,3};private static final String KEY="servo";
 public ServoActuatorBlock(Properties p){super(p);registerDefaultState(stateDefinition.any().setValue(FACING,Direction.NORTH).setValue(SLEW,0));}@Override public MapCodec<ServoActuatorBlock> codec(){return RedstoneEngineering.SERVO_ACTUATOR_CODEC.value();}@Override public BlockState getStateForPlacement(BlockPlaceContext c){return defaultBlockState().setValue(FACING,c.getHorizontalDirection().getOpposite());}@Override protected void createBlockStateDefinition(StateDefinition.Builder<Block,BlockState>b){b.add(FACING,SLEW);}
 @Override public boolean canConnectRedstone(BlockState s,BlockGetter l,BlockPos p,@Nullable Direction d){if(d==null)return false;Direction front=s.getValue(FACING),back=front.getOpposite(),right=switch(front){case NORTH->Direction.EAST;case EAST->Direction.SOUTH;case SOUTH->Direction.WEST;case WEST->Direction.NORTH;default->Direction.EAST;};Direction physical=d.getOpposite();return physical==back||physical==right;}
 private int read(Level l,BlockPos p,Direction d){return Math.max(0,Math.min(15,l.getSignal(p.relative(d),d)));}
 @Override protected void onPlace(BlockState s,Level l,BlockPos p,BlockState o,boolean m){super.onPlace(s,l,p,o,m);if(l instanceof ServerLevel sl)sl.scheduleTick(p,this,2);}
 @Override protected void tick(BlockState s,ServerLevel l,BlockPos p,RandomSource rnd){int[]r=RuntimeIntStore.get(l,KEY,p,13);Direction front=s.getValue(FACING),back=front.getOpposite(),right=switch(front){case NORTH->Direction.EAST;case EAST->Direction.SOUTH;case SOUTH->Direction.WEST;case WEST->Direction.NORTH;default->Direction.EAST;};int newTarget=read(l,p,back);int now=(int)Math.min(Integer.MAX_VALUE,l.getGameTime());if(newTarget!=r[1]){r[6]++;r[7]=now;r[8]=r[0];r[9]=newTarget;r[10]=0;r[11]=0;}r[1]=newTarget;r[4]=read(l,p,right)>0?1:0;int old=r[0];if(r[4]==0){int step=STEP[s.getValue(SLEW)];if(r[0]<r[1])r[0]=Math.min(r[1],r[0]+step);else if(r[0]>r[1])r[0]=Math.max(r[1],r[0]-step);}r[2]=r[0]-old;r[3]=r[1]-r[0];r[12]+=Math.abs(r[2]);r[10]=Math.max(r[10],Math.abs(r[2]));if(r[3]==0&&old!=r[0]){r[11]=Math.max(1,now-r[7]);}if(r[3]!=0&&r[2]==0&&r[4]==0)r[5]++;l.updateNeighborsAt(p,this);l.scheduleTick(p,this,2);}
 @Override protected InteractionResult useWithoutItem(BlockState s,Level l,BlockPos p,Player pl,BlockHitResult h){if(!l.isClientSide){if(pl.isShiftKeyDown()){int[]r=RuntimeIntStore.get(l,KEY,p,13);for(int i=0;i<r.length;i++)r[i]=0;pl.displayClientMessage(Component.literal("Servo homed; trajectory diagnostics reset"),true);}else{int n=(s.getValue(SLEW)+1)%3;BlockState ns=s.setValue(SLEW,n);l.setBlock(p,ns,Block.UPDATE_CLIENTS);int[]r=RuntimeIntStore.get(l,KEY,p,13);pl.displayClientMessage(Component.literal("Servo pos="+r[0]+" target="+r[1]+" velocity="+r[2]+" error="+r[3]+" slew="+STEP[n]+"/2t "+(r[4]!=0?"INHIBITED":"RUN")+" | trajectory commands="+r[6]+" last "+r[8]+"→"+r[9]+" settle="+r[11]+"t vmax="+r[10]+" travel="+r[12]+" | RIGHT=inhibit"),true);}}return InteractionResult.sidedSuccess(l.isClientSide);}
}
